import os

from dotenv import load_dotenv
from google import genai

load_dotenv()


def generate_ai_summary(apk_data, risk_result):

    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY is not set. Add it to .env."
        )

    model = "gemini-3.5-flash"
    client = genai.Client(api_key=api_key)

    findings_text = "\n".join(
        f"- {f['permission']} | {f['severity']} | {f['reason']}"
        for f in risk_result["findings"]
    ) or "- No suspicious findings were generated."

    prompt = f"""
You are the AI explanation layer of PermissionLens,
an Android privacy and permission analysis system.

Application:
{apk_data.get("app_name", "Unknown")}

Application purpose:
{apk_data.get("app_purpose", "Unknown")}

Detected permissions:
{risk_result["permissions_checked"]}

Risk score:
{risk_result["risk_score"]}/100

Risk level:
{risk_result["risk_level"]}

Findings generated by the PermissionLens risk engine:
{findings_text}

Write a concise security summary for a non-technical user.

Explain:
1. What the application is requesting.
2. Which requests are unusual or sensitive.
3. Why they may be unnecessary for the stated purpose.
4. What privacy/security concern they could create.
5. Give a practical recommendation.

Rules:
- Do NOT change the risk score.
- Do NOT invent permissions or behavior.
- Do NOT call the application malware merely because permissions are unusual.
- Clearly distinguish unusual behavior from confirmed malicious behavior.
- Keep the response around 100-150 words.
"""

    response = client.models.generate_content(
        model=model,
        contents=prompt
    )

    return response.text.strip()